DROP TABLE IF EXISTS PUBLIC.HITS;

CREATE TABLE IF NOT EXISTS PUBLIC.HITS
(
    ID        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    APP       CHARACTER VARYING                            NOT NULL,
    URI       CHARACTER VARYING                            NOT NULL,
    IP        CHARACTER VARYING                            NOT NULL,
    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE                  NOT NULL
);