INSERT INTO PUBLIC.STATES
(ID, NAME)
VALUES (0, 'PENDING'),
       (1, 'PUBLISHED'),
       (2, 'CANCELED');
INSERT INTO PUBLIC.STATUSES
(ID, NAME)
VALUES (0, 'PENDING'),
       (1, 'REJECTED'),
       (2, 'CONFIRMED'),
       (3, 'CANCELED');