DROP TABLE  IF EXISTS PUBLIC.USERS;

CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    ID    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NAME  CHARACTER VARYING                            NOT NULL,
    EMAIL CHARACTER VARYING UNIQUE                     NOT NULL
);

