DROP TABLE IF EXISTS PUBLIC.EVENTS;
DROP TABLE IF EXISTS PUBLIC.LOCATIONS;
DROP TABLE IF EXISTS PUBLIC.CATEGORIES;
DROP TABLE IF EXISTS PUBLIC.USERS;

CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    ID    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NAME  CHARACTER VARYING                            NOT NULL,
    EMAIL CHARACTER VARYING UNIQUE                     NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.CATEGORIES
(
    ID   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NAME CHARACTER VARYING UNIQUE                     NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.LOCATIONS
(
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    LOCATION_LAT FLOAT                                        NOT NULL,
    LOCATION_LON FLOAT                                        NOT NULL

);

CREATE TABLE IF NOT EXISTS PUBLIC.EVENTS
(
    ID                 INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    ANNOTATION         CHARACTER VARYING                            NOT NULL,
    CATEGORY_ID        INTEGER REFERENCES PUBLIC.CATEGORIES (ID),
    DESCRIPTION        CHARACTER VARYING                            NOT NULL,
    EVENT_DATE         TIMESTAMP WITHOUT TIME ZONE,
    LOCATION_ID        INTEGER REFERENCES PUBLIC.LOCATIONS (ID),
--     LOCATION_LAT       FLOAT                                        NOT NULL,
--     LOCATION_LON       FLOAT                                        NOT NULL,
    PAID               BOOLEAN,
    PARTICIPANT_LIMIT  INTEGER,
    REQUEST_MODERATION BOOLEAN,
    TITLE              CHARACTER VARYING                            NOT NULL
);